# Generated by Django 5.2.5 on 2025-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Equipment', 'Equipment'), ('Chemicals', 'Chemicals'), ('Feeds', 'Feeds'), ('Tools', 'Tools'), ('Other', 'Other')], default='Seeds', max_length=50)),
                ('description', models.TextField(blank=True, default='No description available.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('seller', models.CharField(default='Unknown Dealer', max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('barcode', models.CharField(default='000000000000', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
