# Generated by Django 5.2.5 on 2025-09-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Request', 'verbose_name_plural': 'Verification Requests'},
        ),
        migrations.AlterModelOptions(
            name='verifiedproduct',
            options={'ordering': ['product__name'], 'verbose_name': 'Verified Product', 'verbose_name_plural': 'Verified Products'},
        ),
    ]
